// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(YolcuDbContext))]
    [Migration("20250621125505_y6")]
    partial class y6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.GecmisBankaIslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bakiye")
                        .HasColumnType("int");

                    b.Property<int>("KartNumarasi")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("YolcuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YolcuId");

                    b.ToTable("gecmisBankaIslemleris");
                });

            modelBuilder.Entity("Entities.KrediKarti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuvenlikKodu")
                        .HasColumnType("int");

                    b.Property<string>("KartNumarasi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("KartSahibi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Tutar")
                        .HasColumnType("int");

                    b.Property<int?>("YolcuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YolcuId");

                    b.ToTable("krediKartis");
                });

            modelBuilder.Entity("Entities.Yolcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Bakiye")
                        .HasColumnType("int");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullanıcıKodu")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoyAd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("yolcus");
                });

            modelBuilder.Entity("Entities.GecmisBankaIslemleri", b =>
                {
                    b.HasOne("Entities.Yolcu", "Yolcu")
                        .WithMany("GecmisBankaIslemleris")
                        .HasForeignKey("YolcuId");

                    b.Navigation("Yolcu");
                });

            modelBuilder.Entity("Entities.KrediKarti", b =>
                {
                    b.HasOne("Entities.Yolcu", "Yolcu")
                        .WithMany("KrediKartis")
                        .HasForeignKey("YolcuId");

                    b.Navigation("Yolcu");
                });

            modelBuilder.Entity("Entities.Yolcu", b =>
                {
                    b.Navigation("GecmisBankaIslemleris");

                    b.Navigation("KrediKartis");
                });
#pragma warning restore 612, 618
        }
    }
}
